### ISSUE TITLE
Compiling errors on vscode on macOS

### ISSUE THREAD

**Issue by dayfinihzy** [unpbook/unpv13e#8]
/usr/bin/clang++ -std=gnu++14 -fcolor-diagnostics -fansi-escape-codes -g /Users/houzhiyang/Desktop/projectC/hw/socket.cpp -o /Users/houzhiyang/Desktop/projectC/hw/socket -std=c++11 -lunp
Undefined symbols for architecture x86_64:
  "Bind(int, sockaddr const*, unsigned int)", referenced from:
      _main in socket-5d6d69.o
  "Close(int)", referenced from:
      _main in socket-5d6d69.o
  "Write(int, void*, unsigned long)", referenced from:
      _main in socket-5d6d69.o
  "Accept(int, sockaddr*, unsigned int*)", referenced from:
      _main in socket-5d6d69.o
  "Listen(int, int)", referenced from:
      _main in socket-5d6d69.o
  "Socket(int, int, int)", referenced from:
      _main in socket-5d6d69.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

What should I do?I have tried adding the - lunp option, but nothing to happen

**Comment by andyrudoff** [comment]
I just confirmed that on MacOS Sonoma (14.0), following the build instructions in the top-level README still works.  Running those instructions from a terminal built the examples as expected.  Not sure about using VScode, since this code was written almost 20 years before VScode -- but you'll have to convince VScode to execute the steps in the README in that order.  Based on the the short snippet you included, my best guess is that you are not including libunp.a on the link line (the Makefiles include the .a file explicitly, so adding -lunp is not the same thing).  When I run the README instructions, the final link line is: `gcc -I../lib -g -O2 -D_REENTRANT -Wall -o byteorder byteorder.o ../libunp.a -lresolv -lpthread`

My advice is to first confirm that the README instructions work on your machine (run them from a terminal) and then try to figure out which steps are different when you use VScode.  If you come up with a change that makes VScode follow the steps correctly, please let us know!

**Comment by dayfinihzy** [comment]
Following your suggestion, I run the README instructions on my machine (run them from a terminal).Running ./daytimetcpsrc can return real time to the client program 'daytimetcpcli'. 
<img width="1115" alt="image" src="https://github.com/unpbook/unpv13e/assets/44896247/82d685fb-0d37-46fb-b4fc-2b76750981cb">
I am continuing to verify if the sample program of the book can be run on the terminal.

**Comment by dayfinihzy** [comment]
<img width="1083" alt="image" src="https://github.com/unpbook/unpv13e/assets/44896247/b210d52b-becf-4f42-9d84-91c51a6b7f1e">
I followed the compilation instructions you provided for the sample program in book and obtained the same error message on VSCode. Should I download the "unpv13e" repo again and follow README again?

**Comment by andyrudoff** [comment]
Sorry, you're not giving me enough information to help.  The examples were designed to work from the terminal shell, following the README.  I don't have any idea what steps you're taking to build them from VScode, but if using the terminal works, it should be showing you all the necessary steps to use the examples.  Making them work under VScode (or any other IDE) requires figuring out how to configure things correctly and nobody has done that, so it is your decision on whether to use the terminal or do the work to make it run under VScode.

Remember, these are just examples -- you can start a new project in your favorite IDE and use the examples to help you write UNIX networking code in C, even if the examples don't build in your IDE.
